Traceback (most recent call last):
  File "/Users/snehaes/Data Science/income_prediction/app.py", line 18, in prediction
    return render_template("form.html")
  File "/Users/snehaes/Data Science/income_prediction/venv/lib/python3.9/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/snehaes/Data Science/income_prediction/venv/lib/python3.9/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/snehaes/Data Science/income_prediction/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/Users/snehaes/Data Science/income_prediction/venv/lib/python3.9/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/snehaes/Data Science/income_prediction/templates/form.html", line 107, in top-level template code
    <form action="{{url_for('predict')}}" method="POST">
  File "/Users/snehaes/Data Science/income_prediction/venv/lib/python3.9/site-packages/flask/app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "/Users/snehaes/Data Science/income_prediction/venv/lib/python3.9/site-packages/flask/app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "/Users/snehaes/Data Science/income_prediction/venv/lib/python3.9/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'predict'. Did you mean 'prediction' instead?
